name: spark

services:
  spark-master:
    build:
      context: ./docker/spark
      dockerfile: master.Dockerfile
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2G"
        reservations:
          cpus: "1"
          memory: "1G"
    hostname: spark-master
    ports:
      - 8080:8080
      - 7077:7077
  spark-worker-1:
    build:
      context: ./docker/spark
      dockerfile: worker.Dockerfile
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2G"
        reservations:
          cpus: "1"
          memory: "1G"
    hostname: spark-worker
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
    ports:
      - 8081:8081
    depends_on:
      - spark-master