name: opentelemetry
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    labels:
      breeze.description: "Integration required for OTEL/opentelemetry hooks."
    command: [--config=/etc/otelcol-contrib/config.yml]
    depends_on:
      kibana:
        condition: service_healthy
    volumes:
      - ./config/otelcol-contrib/config.yml:/etc/otelcol-contrib/config.yml:ro
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
  prometheus:
    image: prom/prometheus
    depends_on:
      kibana:
        condition: service_healthy
    user: "0"
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
  # grafana:
  #   image: grafana/grafana:8.2.4
  #   environment:
  #     GF_AUTH_ANONYMOUS_ENABLED: true
  #     GF_AUTH_ANONYMOUS_ORG_NAME: "Main Org."
  #     GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
  #     GF_PATHS_PROVISIONING: /grafana/provisioning
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - grafana-volume-data:/grafana
  #     - grafana-volume-datasources:/grafana/datasources
  #     - grafana-volume-dashboards:/grafana/dashboards
  #     - grafana-volume-provisioning:/grafana/provisioning
  # jaeger:
  #   image: jaegertracing/all-in-one:1.57
  #   container_name: "breeze-jaeger"
  #   environment:
  #     COLLECTOR_OTLP_ENABLED: true
  #     COLLLECTOR_ZIPKIN_HOST_PORT: 9411
  #   ports:
  #     - "16686:16686"
  #     - "4317:4317"
  #     - "4318:4318"
  #     - "9422:9422"

volumes:
  grafana-volume-data:
    driver: local
  grafana-volume-datasources:
    driver: local
  grafana-volume-dashboards:
    driver: local
  grafana-volume-provisioning:
    driver: local
  prometheus-data:
    driver: local